# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: solita/napote-circleci:latest
      - image: solita/napotedb:latest

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      OTE_BASE_URL: "http://localhost:8080"
      OTE_DB_URL: "jdbc:postgresql://localhost:5432/napotetest"
      OTE_DB_USERNAME: "napote"
      OTE_DB_PASSWORD: ""
      OTE_AUTH_SHARED_SECRET: "test"
      OTE_FLAGS: "#{:ote-login :ote-operators-list :sea-routes :pre-notice :gtfs-import :ote-register}"
      CHOUETTE_PATH: "/tmp/chouette/"
      NETEX_CONVERSION_WORKPATH: "/tmp/ote/netex-conversion/"

    steps:
      - checkout

      - restore_cache:
          keys:
          - v4-dependencies-{{ .Branch }}-{{ checksum "ote/project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v4-dependencies-{{ .Branch }}
          - v4-dependencies-

      - run:
          name: Lein deps
          command: cd ote && lein deps

      - save_cache:
          key: v4-dependencies-{{ .Branch }}-{{ checksum "ote/project.clj" }}
          paths:
            - ~/.m2

      # setup database
      - run: aws s3 cp s3://ote-assets/places/finnish_municipalities.csv database/finnish_municipalities.csv
      - run: aws s3 cp s3://ote-assets/places/maakunnat.csv database/maakunnat.csv
      - run: aws s3 cp s3://ote-assets/places/finnish_postal_codes.csv database/finnish_postal_codes.csv
      - run: aws s3 cp s3://ote-assets/places/spatial_relations_places.csv database/spatial_relations_places.csv
      - run: cd database && sh circleci_setup.sh


      # run tests!
      - run:
          name: Setup config.edn for tests
          command: envsubst < .circleci/config.edn.envsubst > ote/config.edn

      - run:
          name: Run tests
          command: cd ote && cat config.edn && lein test

      - run:
          name: Make production build of OTE app
          command: cd ote && lein production

      - run:
          name: Configure build
          command: |
            set +e
            mkdir /tmp/ote && envsubst < .circleci/config.edn.envsubst > /tmp/ote/config.edn
            mv ote/target/ote-1.4-SNAPSHOT-standalone.jar /tmp/ote/ote.jar

      - run:
          name: Deploy build artifacts
          command: |
            mkdir deploy
            ln ote/config.edn deploy/ote-${CIRCLE_BRANCH}-config.edn
            ln /tmp/ote/ote.jar deploy/ote-${CIRCLE_BRANCH}.jar
            pg_dump -h localhost -p 5432 -U postgres -Z 1 napote > deploy/ote-${CIRCLE_BRANCH}-pgdump.gz
            aws s3 cp deploy s3://napote-circleci/build-artifacts --recursive

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: /tmp/ote
          # Must be relative path from root
          paths:
            - ote.jar
            - config.edn

  e2e-pr:
    docker:
      - image: solita/napote-circleci:latest
      - image: solita/napotedb:latest

    working_directory: ~/repo

    environment:
      ## this enables colors + fixes failing unit tests (they say)
      TERM: "xterm"
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      CYPRESS_BASE_URL: "http://localhost:3000"
      CYPRESS_NAP_LOGIN: "admin@napoteadmin123.com"
      CYPRESS_NAP_PASSWORD: "admin"
      CYPRESS_NAP_NORMALUSERLOGIN: "normaluser"
      CYPRESS_NAP_NORMALUSERPWD: "password"
      #DEBUG: "cypress*"

    steps:
      - checkout

      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/ote

      # setup database
      - run: aws s3 cp s3://ote-assets/places/finnish_municipalities.csv database/finnish_municipalities.csv
      - run: aws s3 cp s3://ote-assets/places/maakunnat.csv database/maakunnat.csv
      - run: cd database && sh circleci_setup.sh

      - restore_cache:
          keys:
            - v4-npm-deps-

      - run:
          name: Install Cypress
          command: npm i cypress@3.x && $(npm bin)/cypress verify

      - save_cache:
          key: v4-npm-deps-
          paths:
            - node_modules

      - run:
          name: Run OTE app
          command: cd /tmp/ote && java -jar ote.jar
          background: true

      - run:
          name: Wait for OTE app to respond
          command: |
            while ! nc -z localhost 3000; do
              sleep 0.5;
            done;

      # Note: When running with chrome, it seems we cannot record a video. Only Electron browser can record a video.
      # Note 2: If you change this invocation, be sure to also make a corresponding change in the internal deployment CI.
      - run:
          name: Run all tests for a pull request
          command: $(npm bin)/cypress run --record false
          
      - run:
          when: on_fail
          name: Save any screenshots from test failures to s3
          command: if test -d cypress/screenshots; then ls -la cypress/screenshots; zipfn=screenshots-${CIRCLE_BRANCH}.`date --iso=seconds`.zip; zip -0r $zipfn cypress/screenshots && aws s3 cp $zipfn s3://napote-circleci/build-artifacts/$zipfn; echo screenshots available from https://napote-circleci.s3.amazonaws.com/build-artifacts/$zipfn; else echo no screenshot dir; fi


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # e2e commented out here because of flakiness. uncomment in your branch to run them in circleci.
      # - e2e-pr:
      #    requires:
      #      - build
